### PR TITLE
Install Custom Fields for Custom Posts.

### PR DESCRIPTION
**Pull request by shottah**
Set up advance custom fields plugin.

### CODE REVIEW

**Comment by shottah** [comment]
Changes to the post editor screen is not affected by code and is stored in the database. sql file needs to be excluded from `.gitignore` @asayee0

**Comment by jefroy** [comment]
I believe the sql file keeps track of post data and post metadata, which does not seem too expensive to track on the repo. for the sake of development, i think it might be good to include it, but at deployment, omit it. @asayee0  @matabeitt

**Comment by shottah** [comment]
This is in progress. Just double check that we have all the necessary files
and the `gitignore` has no errors.

**Comment by matabeitt** [comment]
Closes #25

**Pull request merged**
