### PR TITLE
Feature 62 - Adjustments to archive.php

### LINKED ISSUE #62: Adjustments and fixes to archive.php
**This list will be broken up and moved soon to its respective branches** 

`archive.php` (accessible if you click on posts by adminuser for example)
- [x]  Change the title on the page to something more presentable
- [x]  Display the type of post (anime, or review) per post

`archive.php` (accessible if you click on posts by adminuser for example)
- [ ] Remove the empty genre box for post type: Review
- [ ] **FIX BUG**: clicking on any author shows all posts created by all authors, rather than just the one that was clicked

`front-page.php`
- [ ] Right sidebar should only show one tab (currently shows latest, popular, trending). The other tabs are pointless without the relevant functionalities.
- [ ] Right sidebar should show more info per anime
- [ ] ~~Should we remove the right sidebar below it (the one that starts with the search bar) its ugly af~~
- [x] Add a menu (#39) 

Pages
- [ ] Reviews (archive) page
- [ ] Show all anime (archive) page
- [ ] About page
- [ ] Sign up page

`anime-single.php`
- [ ] Center featured image (see One Piece for example; image is left justified)
- [ ] Show the original author of the post at top

Reviews section in `anime-single.php`
- [ ] Remove the word "random"
- [ ] Show reviewer name and date
- [ ] Show reviewer profile picture
- [ ] Implement "like" button functionality? (could take a while)

### PR DESCRIPTION
**Pull request by asayee0**
Closes #62

### CODE REVIEW

**Comment by asayee0** [comment]
> archive.php (accessible if you click on posts by adminuser for example)
> 
> * [x]  Change the title on the page to something more presentable
> * [x]  Display the type of post (anime, or review) per post

`archive.php` (accessible if you click on posts by adminuser for example)
- [ ] Remove the empty genre box for post type: Review
- [ ] **FIX BUG**: clicking on any author shows all posts created by all authors, rather than just the one that was clicked

`front-page.php`
- [ ] Right sidebar should only show one tab (currently shows latest, popular, trending). The other tabs are pointless without the relevant functionalities.
- [ ] Right sidebar should show more info per anime
- [ ] Should we remove the right sidebar below it (the one that starts with the search bar) its ugly af
- [ ] Add a menu (#39) 

Pages
- [ ] Reviews (archive) page
- [ ] Show all anime (archive) page
- [ ] About page
- [ ] Sign up page

`anime-single.php`
- [ ] Center featured image (see One Piece for example; image is left justified)
- [ ] Show the original author of the post at top

Reviews section in `anime-single.php`
- [ ] Remove the word "random"
- [ ] Show reviewer name and date
- [ ] Show reviewer profile picture
- [ ] Implement "like" button functionality? (could take a while)

**Comment by shottah** [comment]
Removing the `Latest/Popular/Trending` tabs will leave a large empty space on the home screen.
You can remove the `Sidebar Widget`, also consider editing what is contained in the widget using the `Customise` functionality of WP.

**Comment by asayee0** [comment]
> Removing the `Latest/Popular/Trending` tabs will leave a large empty space on the home screen.
> You can remove the `Sidebar Widget`, also consider editing what is contained in the widget using the `Customise` functionality of WP.

No i meant remove two of the tabs, so it still at least displays `Latest`

And i'll do `customise` you right

**Comment by shottah** [comment]
Is this branch solely for displaying an author-based archive file? If so, I will take it over when I do work on the site shortly.

**Pull request merged**
