### PR TITLE
Added featured images to anime

### LINKED ISSUE #51: Add featured images to custom anime post
Animes should have featured images to use on the carousel.
If the no featured image is set, it should default to some image.

### LINKED ISSUE #58: Add Featured Images to Custom Post Types

### PR DESCRIPTION
**Pull request by asayee0**
Closes #58 and #51

### CODE REVIEW

**Comment by asayee0** [comment]
This is actually ready to merge @matabeitt 
The jumping to IDs that I was doing earlier should be a different issue.

**Review by shottah — CHANGES_REQUESTED** [review]
We should still keep the thumbnail presets defined.

**Comment by asayee0** [comment]
> We should still keep the thumbnail presets defined.

I was considering leaving it, but it's bad design to leave unused code that may or may not be used in the future. And we're getting marked on OOP principles she said.

**Comment by shottah** [comment]
Wtf does that mean dog we didnt even learn how to do a class in php

**Comment by asayee0** [comment]
> Wtf does that mean dog we didnt even learn how to do a class in php

It was like the first topic we did in OOP2, where she taught us that having unused features in your code for "future purposes" is bad design.
Since OOP2 was primarily a design course... the principles translate here as well.

**Comment by shottah** [comment]
What about other SOLID and DRY principles? Should we be doing a major refactor for all of those considerations too?

**Pull request merged**
