### PR TITLE
Merge custom roles

### LINKED ISSUE #7: Create User Roles
- [x] 2 Types of Users
- [x]  User Permissions

### PR DESCRIPTION
**Pull request by asayee0**
Resolves #7

### CODE REVIEW

**Comment by asayee0** [comment]
If you approve, merge and delete branch

**Comment by asayee0** [comment]
Accidental close after comment

**Review by shottah — CHANGES_REQUESTED** [review]
I'm seeing that code was removed from the parent theme but not put into child theme. What's up?

**Comment by asayee0** [comment]
The code that I removed was commented out when it was originally in the file, so it didn't actually do anything. I created a new functions.php for child theme because it's better design to put any additional features in the child.

**Comment by asayee0** [comment]
Changes made to update .gitignore

**Review by shottah — APPROVED** [review]
Good stuff.

**Pull request merged**
